test-lint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,6 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
-
 cd frontend && npm run lint
+if [ $? -ne 0 ]; then
+  echo "ESLint failed. Commit aborted."
+  exit 1
+fi
